all:
    MUX_DIR: "/scr1/users/leej39/mux_fake"
    PROJECT_DIR: "/scr1/users/leej39/fake"
    MAPPING: "Goldberg_Run_1_Habtezion_Run_5_Bjornsson_Run_1_mapping_file.tsv"
    ADMIN_EMAIL: "junglee0713@gmail.com"

demux:
    MISMATCH: 0
    DEMUX: "demultiplexed_fastq"
    DEMUX_GZ: "demultiplexed_fastq_gz"
    TOTAL_READS: "total_read_counts.tsv"
    MANIFEST: "manifest.csv"

import:
    QIIME: "QIIME_output"

denoise:
    DENOISE: "denoise"
    FEATURE_TABLE: "feature_table"
    REPSEQ : "representative_seq_fasta"
    DADA2:
        trim_left_f: 0
        trunc_len_f: 240
        trim_left_r: 0
        trunc_len_r: 240
        n_threads: 1

taxonomy:
    TAXONOMY: "taxonomy"
    CLASSIFIER_FP: "/home/leej39/16S_QIIME2/QIIME2_data/gg-13-8-99-nb-classifier.qza"            

diversity:
    sampling_depth: 30
    core_metrics: "core-metrics"    

unassign:
    unassign_out: "unassigned"
    unassigner_species_fp: "/home/leej39/16S_QIIME2/unassign_data/unassigner_species.fasta"

report:
    report: "Basic_Bioinformatics_Report"

